apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mjazgk1wg-nodejs 
  janus-idp.io/tekton: mjazgk1wg-nodejs
  backstage.io/kubernetes-id: mjazgk1wg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mjazgk1wg-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  