apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mjazgk1wg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mjazgk1wg-nodejs 
  name: mjazgk1wg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mjazgk1wg-nodejs 
